const express = require('express');
const router = express.Router();
const usersController = require('../controllers/usersController');
router.get('/user', usersController.user);
router.get('/orders', usersController.orders);
router.get('/ordersBought', usersController.ordersBought);
router.get('/bookings', usersController.bookings);
router.get('/favorites', usersController.favorites);
router.get('/payment/:id', usersController.payment);
router.get('/tables', usersController.tables);
router.post('/addOrder', usersController.addOrder);
router.post('/addBooking', usersController.addBooking);
router.post('/addFavorite', usersController.addFavorite);
router.post('/addReview', usersController.addReview);
router.put('/updateBooking/:id', usersController.updateBooking);
router.patch('/updateOrder/:id', usersController.updateOrder);
router.patch('/updateReview/:id', usersController.updateReview);
router.delete('/deleteOrder/:id', usersController.deleteOrder);
router.delete('/deleteBooking/:id', usersController.deleteBooking);
router.delete('/deleteFavorite/:id', usersController.deleteFavorite);
router.delete('/deleteReview/:id', usersController.deleteReview);
module.exports = router;